version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scrumw
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/10-init.sql
  springboot:
    depends_on:
      - mysqldb
    build: ./backend
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/scrumw?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root" }'
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2