version: "3.9"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scrumw
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - .data:/var/lib/mysql
    networks:
      - scrumw

  springboot:
    depends_on:
      - mysqldb
    build: ./backend
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/scrumw?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root" }'
    volumes:
      - .m2:/root/.m2
    networks:
      - scrumw

  svelte-app:
    build: ./frontend
    ports:
      - 3000:3000
      - 24678:24678
    networks:
      - scrumw
    environment:
      - NODE_ENV=production
    stdin_open: true

  nginx:
    depends_on:
      - svelte-app
      - springboot
    restart: always
    build: ./nginx
    ports:
      - 8080:80
    networks:
      - scrumw
    links:
      - springboot:api
networks:
  scrumw:
    driver: bridge