spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/scrumw_2"
    username: "root"
    password: ""
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"